// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package employee

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (int32, error)
	CreatePassport(ctx context.Context, arg CreatePassportParams) (int32, error)
	DeleteEmployee(ctx context.Context, id int32) error
	GetDepartmentById(ctx context.Context, id int32) (GetDepartmentByIdRow, error)
	GetEmployeeById(ctx context.Context, id int32) (Employee, error)
	GetEmployeesByCompany(ctx context.Context, companyID pgtype.Int4) ([]GetEmployeesByCompanyRow, error)
	GetEmployeesByCompanyDepartment(ctx context.Context, arg GetEmployeesByCompanyDepartmentParams) ([]GetEmployeesByCompanyDepartmentRow, error)
	GetOrCreateDepartment(ctx context.Context, arg GetOrCreateDepartmentParams) (int32, error)
	GetPassportById(ctx context.Context, id int32) (GetPassportByIdRow, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
	UpdatePassport(ctx context.Context, arg UpdatePassportParams) error
}

var _ Querier = (*Queries)(nil)
